# 1. The Secret Object
apiVersion: v1
kind: Secret
metadata:
  name: app-db-credentials
type: Opaque
data:
  # Values must be base64 encoded
  # 'admin' in base64
  username: YWRtaW4=
  # 'S3cretP@ssw0rd' in base64
  password: UzNjcmV0UEBzc3cwcmQ=

---

# 2. The Pod using the Secret
apiVersion: v1
kind: Pod
metadata:
  name: backend-app
spec:
  containers:
  - name: auth-service
    image: node:18-slim
    env:
      # Defining an environment variable from a Secret key
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: app-db-credentials
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: app-db-credentials
            key: password
